modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
[[mods]] #mandatory
modId="vanillatweaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="VanillaTweaks" #mandatory
updateJSONURL="https://raw.githubusercontent.com/StrikerRockers-Mods/VanillaTweaks/1.14/version.json" #optional
displayURL="http://strikerrocker.github.io/vanillatweaks" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks to Anon10w1z for creating the mod , Subaraki for the textures." #optional
authors="StrikerRocker" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''VanillaTweaks is a Minecraft mod designed to enhance vanilla Minecraft without going overboard. It is designed to be minimally invasive and configurable to create a user experience like none others.'''
[[dependencies.vanillatweaks]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanillatweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanillatweaks]]
        modId="jei"
        mandatory=false
        versionRange="[6,)"
        ordering="NONE"
        side="BOTH"
